app/models/personaje.py
class Personaje:
    def __init__(self,name):
        self.name = name

app/__init__.py
from flask import Flask
from app.config import Config
from flask_bootstrap import Bootstrap
from app.routes.personaje import personajes_ruta

# Función de fábrica
def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    Bootstrap(app)
    app.register_blueprint(personajes_ruta)
    return app

app/routes/personaje.py
from flask import Blueprint,render_template
from app.models.personaje import Personaje
from app.db import db
import requests

personajes_ruta = Blueprint('personajes_ruta',__name__)

@personajes_ruta.route('/')
def index():
    return render_template('index.html')

@personajes_ruta.route('/guardar-personajes')
def guardar_personajes():
    # n es la página del personaje a cargar
    n_pages = 21
    for n in range(1, n_pages + 1):
        url = 'https://rickandmortyapi.com/api/character?page=' + str(n)
        inf_personaje = requests.get(url)

        if inf_personaje.status_code != 200:
            print('No se encontró personaje.')
            continue
        
        inf_personaje_json = inf_personaje.json()

        for personaje in inf_personaje_json['results']:
            if db.personajes.find_one({'id':personaje['id']}) is None:
                db.personajes.insert_one(personaje)

    return render_template('guarda_personajes.html')

@personajes_ruta.route('/mostrar-personajes')
def mostrar_personajes():
    personajes = db.personajes.aggregate([{'$sort':{'id':-1}}])

    return render_template('mostrar_personajes.html',personajes=personajes)

@personajes_ruta.route('/mostrar-personajes/<id>')
def info_perfil(id):
    id = int(id)
    personaje = db.personajes.find_one({'id':id})

    return render_template('info_perfil.html',personaje=personaje)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    

    {% endblock %}
</body>
</html>

app/templates/guarda_personajes.html
{% extends "base.html" %}

{% block title %} Guardado Personajes {% endblock %}

{% block content %}

<h3> Se guardaron los personajes exitosamente en MongoDB. </h3>

<p>
    <a href="{{url_for('personajes_ruta.index')}}">
        Home
    </a>

</p>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %} Proyecto Personajes {% endblock %}

{% block content %}

<h1>Bienvenido al proyeccto de Personajes</h1>

<p>
     
    <a href="{{url_for('personajes_ruta.guardar_personajes')}}">
        Guardar personajes en MongoDB.
    </a>

</p>

<p>
    
    <a href="{{url_for('personajes_ruta.mostrar_personajes')}}">
        Listar personajes.
    </a>

</p>

{% endblock %}

app/templates/info_perfil.html
{% extends "base.html" %}

{% block title %} Perfil de {{personaje.name}} {% endblock %}

{% block content %}

    <a href="{{ url_for('personajes_ruta.mostrar_personajes') }}">Atrás</a>

    <div class="profile">
        <img class="img" src="{{ personaje.image }}"/>
  
    <div class="info">
      <h3>{{ personaje.name }}</h3>

        Estado: 
        {{ personaje.status }}
        {{ personaje.species }} <br>

        Tipo: 
        {{ personaje.type }} <br>

        Género: 
        {{ personaje.gender }} <br>

        Originario de: 
        {{ personaje.origin.name }} <br>

        Last known Location: 
        {{ personaje.location.name }} <br>

        First seen in: <br>
        {{ personaje.episode[0] }} <br>

        Aparece en los episodios: <br>
        {% for episode in personaje.episode %}
            {{ episode }} <br>
        {% endfor %}
        
        Fecha de creación: 
        {{ personaje.created }}
    
    </div>
    </div>



{% endblock %}

app/templates/mostrar_personajes.html
{% extends "base.html" %}

{% block title %} Mostrar Personajes {% endblock %}

{% block content %}

<h1>Listado de personajes</h1>
<p>
    <a href="{{url_for('personajes_ruta.index')}}"> Home </a>
</p>

{% for personaje in personajes %}

    <div class="profile">
        <img class ="img" src="{{ personaje.image }}" width="25%" height="25%" />
    
        <div class="info">
        
        <a href="{{url_for('personajes_ruta.info_perfil',id=personaje.id)}}"> Ver Perfil </a> <br>

        {{ personaje.name }} <br>
        {{ personaje.status }}
        {{ personaje.species }} <br>

        Last known Location: <br>
        {{ personaje.location.name }} <br>

        First seen in: <br>
        {{ personaje.episode[0] }}

    </div>

    </div>

{% endfor %}

{% endblock %}